# Generated by Django 4.1.7 on 2023-03-30 12:24

import django.core.validators
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image_s3_path',
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.user_directory_path, validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
