version: "3.10"

services:
    django:
        tty: true
        build:
            context: .
            dockerfile: Dockerfile
        container_name: django
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        networks:
            - main
        depends_on:
            - postgresql
    postgresql:
        image: postgres
        container_name: postgresql
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        ports:
            - "5432:5432"
        networks:
            - main
        env_file:
            - .env

networks:
    main:

volumes:
    postgres_data:
