version: "3.10"

services:
    django:
        tty: true
        build:
            context: .
            dockerfile: Dockerfile
        container_name: django
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        networks:
            - main
        depends_on:
            - postgresql
    postgresql:
        image: postgres
        container_name: postgresql
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        ports:
            - "5432:5432"
        networks:
            - main
        env_file:
            - .env
    rabbit:
        image: rabbitmq:3.11.11-management-alpine
        hostname: rabbit
        container_name: rabbit
        networks:
            - main
        restart: always
        volumes:
            - ./rabbitmq:/var/lib/rabbitmq/mnesia
        env_file:
            - .env
        ports:
            - "5672:5672"
            - "15672:15672"
#    celery-worker:
#        container_name: celery-worker
#        hostname: celery-worker
#        build: .
#        command: celery -A core worker -l INFO
#        volumes:
#            - ./:/app
#        networks:
#            - main
#        depends_on:
#            - rabbit
#            - django

networks:
    main:

volumes:
    postgres_data:
    rabbit_data:
