version: "3.10"

services:
    django:
        tty: true
        build:
            context: .
            dockerfile: Dockerfile
        container_name: django
        volumes:
            - .:/usr/src/app
        ports:
            - "8000:8000"
        depends_on:
            - pgdb
    pgdb:
        image: postgres
        container_name: pgdb
        ports:
            - "5432:5432"
#        volumes:
#            - ./data/postgres:/var/lib/postgresql/data/
        env_file:
            - .env
