# Generated by Django 4.1.7 on 2023-03-14 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('innotwits', '0003_page_created_post_like_post_reply_to_alter_page_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='created',
        ),
    ]
