# Generated by Django 4.1.7 on 2023-03-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innotwits', '0006_page_is_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(null=True, related_name='likes', to='innotwits.page'),
        ),
    ]
