# Generated by Django 4.1.7 on 2023-03-20 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('innotwits', '0009_alter_post_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreplies',
            name='reply_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='innotwits.page'),
        ),
    ]
