# Generated by Django 4.1.7 on 2023-03-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innotwits', '0013_followerrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='followerrequest',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
