# Generated by Django 4.1.7 on 2023-03-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innotwits', '0014_followerrequest_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='follow_requests',
        ),
        migrations.AlterField(
            model_name='page',
            name='followers',
            field=models.ManyToManyField(related_name='follows', to='innotwits.page'),
        ),
    ]
