# Generated by Django 4.1.7 on 2023-03-22 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('innotwits', '0016_page_follow_requests_alter_page_followers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reply_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='innotwits.post'),
        ),
        migrations.DeleteModel(
            name='PostReplies',
        ),
    ]
