# Generated by Django 4.1.7 on 2023-03-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innotwits', '0017_post_reply_to_delete_postreplies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='unblock_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
