# Generated by Django 4.1.7 on 2023-03-30 12:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innotwits', '0019_alter_page_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/<django.db.models.fields.CharField>/%Y/%m/%d', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
