# Generated by Django 4.2 on 2023-04-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innotwits', '0021_alter_page_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='is_private',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
